name: vo_ninja
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+21

environment:
  sdk: ^3.5.3

dependencies:
  easy_splash_screen: ^1.0.4
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_styled_toast: ^2.2.1  
  shared_preferences: ^2.5.3
  # flutter_native_splash: ^2.4.4
  google_mobile_ads: ^6.0.0
  dio: ^5.9.0
  flutter_localizations:
    sdk: flutter
  intl: any
  image_picker: ^1.2.0
  http: ^1.5.0
  flutter_vector_icons: ^2.0.0
  font_awesome_flutter: ^10.8.0
  url_launcher: ^6.3.2
  firebase_core: ^4.1.1
  firebase_messaging: ^16.0.2
  googleapis_auth: ^2.0.0
  flutter_tts: ^4.2.1
  firebase_auth: ^6.1.0
  firebase_storage: ^13.0.2
  cloud_firestore: ^6.0.2
  faker: ^2.2.0
  loading_overlay: ^0.4.3
  auto_size_text: ^3.0.0
  cached_network_image: ^3.4.1
  path_provider: ^2.1.5
  #awesome_dialog: ^3.2.1
  ntp: ^2.0.0
  syncfusion_flutter_charts: ^28.2.4+1
  flutter_udid: ^4.0.0
  video_player: ^2.10.0
  chewie: ^1.13.0
  gif: ^2.3.0
  connectivity_plus: ^7.0.0
  #flutter_cached_pdfview: ^0.4.3
  facebook_app_events: ^0.20.1
  another_flushbar: ^1.12.32
  confetti: ^0.8.0
  flutter_animate: ^4.5.2
  lottie: ^3.3.1
  device_info_plus: ^12.1.0
  package_info_plus: ^9.0.0
  wakelock_plus: ^1.4.0
  flutter_pdfview: ^1.4.3
  flutter_cache_manager: ^3.4.1
  flutter_smart_dialog: ^4.9.8+9



  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  intl_utils: ^2.8.12


flutter:
  uses-material-design: true
  generate: true

  assets:
   - assets/img/Advanced.png
   - assets/img/Background.png
   - assets/img/basic.png
   - assets/img/f_ninja1.png
   - assets/img/f_ninja2.png
   - assets/img/f_ninja3.png
   - assets/img/f_ninja4.png
   - assets/img/face.png
   - assets/img/fane.png
   - assets/img/intermed.png
   - assets/img/logo.png
   - assets/img/ninja1.png
   - assets/img/ninja2.png
   - assets/img/ninja3.png
   - assets/img/ADs.png
   - assets/img/avatar.png
   - assets/img/avatar2.png
   - assets/img/avatar3.png
   - assets/img/avatar4.png
   - assets/img/avatar5.png
   - assets/img/avatar6.png
   - assets/img/avatar7.png
   - assets/img/Challenge.png
   - assets/img/home.png
   - assets/img/end_learning.png
   - assets/img/apple.png
   - assets/img/task.png
   - assets/img/facebook.png
   - assets/img/instagram.png
   - assets/img/x.png
   - assets/img/tiktok.png
   - assets/img/voninja.png
   - assets/img/splash_voninja.png
  #  - assets/img/background_color.png
   - assets/img/ninja_gif.gif
   - assets/img/intro.gif
   - assets/fonts/JollyLodger-Regular.ttf
   - assets/fonts/njnaruto.ttf
   - lib/l10n/intl_ar.arb
   - lib/l10n/intl_en.arb
   - assets/videos/intro.MP4
   - assets/img/bronze_closed.png
   - assets/img/silver_closed.png
   - assets/img/gold_closed.png
   - assets/img/bronze_open.png
   - assets/img/silver_open.png
   - assets/img/gold_open.png
   - assets/anim/coin_burst.json
   - assets/img/ug_social_codes_1.jpeg
   - assets/img/ug_social_codes_2.jpeg
   - assets/img/ug_cashout_1.jpeg
   - assets/img/ug_cashout_2.jpeg




# flutter_native_splash:
#   color: "#1A3037"  # Background color
#   image: assets/img/background_color.png  # Your splash image
#   android: true
#   ios: true
#   android_12:
#     color: "#1A3037"
#     image: assets/img/background_color.png
flutter_intl:
  enabled: true
