name: vo_ninja
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+10

environment:
  sdk: ^3.5.3

dependencies:
  easy_splash_screen: ^1.0.4
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_styled_toast: ^2.2.1  
  shared_preferences: ^2.3.2
  # flutter_native_splash: ^2.4.4
  google_mobile_ads: ^5.2.0
  dio: ^5.7.0
  intl: ^0.19.0
  image_picker: ^1.1.2
  http: ^1.2.2
  flutter_vector_icons: ^2.0.0
  font_awesome_flutter: ^10.8.0
  url_launcher: ^6.3.1
  firebase_core: ^3.10.0
  firebase_messaging: ^15.2.0
  googleapis_auth: ^1.6.0
  flutter_tts: ^4.2.1
  firebase_auth: ^5.4.1
  firebase_storage: ^12.4.1
  cloud_firestore: ^5.6.2
  faker: ^2.2.0
  loading_overlay: ^0.4.2
  auto_size_text: ^3.0.0
  cached_network_image: ^3.4.1
  path_provider: ^2.1.5
  package_info_plus: ^8.2.0
  awesome_dialog: ^3.2.1
  ntp: ^2.0.0
  syncfusion_flutter_charts: ^28.2.4+1
  flutter_udid: ^4.0.0
  device_info_plus: ^11.3.0
  video_player: ^2.9.3
  chewie: ^1.10.0
  gif: ^2.3.0
  connectivity_plus: ^6.1.3

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  intl_utils: ^2.6.0


flutter:
  uses-material-design: true
  generate: true

  assets:
   - assets/img/Advanced.png
   - assets/img/Background.png
   - assets/img/basic.png
   - assets/img/f_ninja1.png
   - assets/img/f_ninja2.png
   - assets/img/f_ninja3.png
   - assets/img/f_ninja4.png
   - assets/img/face.png
   - assets/img/fane.png
   - assets/img/intermed.png
   - assets/img/logo.png
   - assets/img/ninja1.png
   - assets/img/ninja2.png
   - assets/img/ninja3.png
   - assets/img/ADs.png
   - assets/img/avatar.png
   - assets/img/avatar2.png
   - assets/img/avatar3.png
   - assets/img/avatar4.png
   - assets/img/avatar5.png
   - assets/img/avatar6.png
   - assets/img/avatar7.png
   - assets/img/Challenge.png
   - assets/img/home.png
   - assets/img/end_learning.png
   - assets/img/apple.png
   - assets/img/task.png
   - assets/img/facebook.png
   - assets/img/instagram.png
   - assets/img/x.png
   - assets/img/tiktok.png
   - assets/img/voninja.png
   - assets/img/splash_voninja.png
  #  - assets/img/background_color.png
   - assets/img/ninja_gif.gif
   - assets/img/intro.gif
   - assets/fonts/JollyLodger-Regular.ttf
   - assets/fonts/njnaruto.ttf
   - lib/l10n/intl_ar.arb
   - lib/l10n/intl_en.arb
   - assets/videos/intro.MP4




# flutter_native_splash:
#   color: "#1A3037"  # Background color
#   image: assets/img/background_color.png  # Your splash image
#   android: true
#   ios: true
#   android_12:
#     color: "#1A3037"
#     image: assets/img/background_color.png
