// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADWQpJpGVDZLJ37eZEan6Z8FxDUfGbuSI',
    appId: '1:910113947104:web:183c6c133b3ccb38807f85',
    messagingSenderId: '910113947104',
    projectId: 'voninja-messaging',
    authDomain: 'voninja-messaging.firebaseapp.com',
    storageBucket: 'voninja-messaging.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqXiPhHo2ZvWrxuXtSdja5s-m2AG9lxi8',
    appId: '1:910113947104:android:9f37e61e4efb90c5807f85',
    messagingSenderId: '910113947104',
    projectId: 'voninja-messaging',
    storageBucket: 'voninja-messaging.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLi4z3ExlroY3CUaLDD1fchLU-wDId2Fs',
    appId: '1:910113947104:ios:d95fbfd061484e93807f85',
    messagingSenderId: '910113947104',
    projectId: 'voninja-messaging',
    storageBucket: 'voninja-messaging.firebasestorage.app',
    iosBundleId: 'com.example.voNinja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLi4z3ExlroY3CUaLDD1fchLU-wDId2Fs',
    appId: '1:910113947104:ios:d95fbfd061484e93807f85',
    messagingSenderId: '910113947104',
    projectId: 'voninja-messaging',
    storageBucket: 'voninja-messaging.firebasestorage.app',
    iosBundleId: 'com.example.voNinja',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADWQpJpGVDZLJ37eZEan6Z8FxDUfGbuSI',
    appId: '1:910113947104:web:53b80f1b8eb779ee807f85',
    messagingSenderId: '910113947104',
    projectId: 'voninja-messaging',
    authDomain: 'voninja-messaging.firebaseapp.com',
    storageBucket: 'voninja-messaging.firebasestorage.app',
  );

}